version: "3.8"

services:
  # api:
  #   build:
  #     context: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  db:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  cache:
    image: redis/redis-stack-server:6.2.6-v17-arm64
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env

volumes:
  db-data:
  redis-data:
