services:
  db:
    image: postgres:alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payroll
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
